### ISSUE TITLE
Definição dos equipamentos (a implementar)

### ISSUE THREAD

**Issue by ghost** [feira-de-jogos/equipamentos#1]
- _Dispenser_?
- Mini _arcade_?
- _Pinball_?

**Comment by henriquecmh** [comment]
Estou trabalhando no levantamento do que podemos implementar, a ideia é desenvolver os três ainda que não possamos implementar fisicamente todos, já vamos delineando o formato, linguagem, _hardware_, requisitos, interfaces, etc...

**Comment by ederson-torresini** [comment]
_Vending machine_ pronta. Demais equipamentos ficarão para o semestre 2024.1.
